### Normaliztion


In [6]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler


In [11]:
x=np.array([[10],[20],[30],[40],[100]])
scaler=StandardScaler()
X_transformed=scaler.fit_transform(x)
print(X_transformed)


[[-0.9486833 ]
 [-0.63245553]
 [-0.31622777]
 [ 0.        ]
 [ 1.8973666 ]]


In [12]:
x=np.array([[10],[20],[30],[40],[100]])
scaler=MinMaxScaler(feature_range=(0,1))
X_transformed=scaler.fit_transform(x)
print(X_transformed)

[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [1.        ]]


In [13]:
x=np.array([[10],[20],[30],[40],[100]])
j=len(str(np.max(np.abs(x))))
X_transformed=x/10**j
print(X_transformed)

[[0.01]
 [0.02]
 [0.03]
 [0.04]
 [0.1 ]]


In [14]:
x=np.array([[10],[20],[30],[40],[100]])
j=len(str(np.max(np.abs(x))))
X_transformed=x/10**j
print(X_transformed)

[[0.01]
 [0.02]
 [0.03]
 [0.04]
 [0.1 ]]


### feature encoding

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cities=['Kathmandu','Pokhara','Biratnagar']
encoded=le.fit_transform(cities)
print(encoded)

[1 2 0]


In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['poor','fair','good']])# 1row 3 column
quality=[['poor'],['fair'],['good']]#2d array (list of list) 3 row 1 column
encoded=encoder.fit_transform(quality)
print(encoded)

[[0.]
 [1.]
 [2.]]
